"""initial_schema

Revision ID: c28b02963aa7
Revises: None
Create Date: 2026-06-21 23:40:18.556170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c28b02963aa7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge_references',
    sa.Column('badge_id', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unlock_condition', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('badge_id')
    )
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('company_type', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_interview_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_key', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=False),
    sa.Column('interview_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('question_style_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluation_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('leadership_principles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('estimated_ctc_min_lpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('estimated_ctc_max_lpa', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_interview_profiles_profile_key'), 'company_interview_profiles', ['profile_key'], unique=True)
    op.create_table('job_listings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_tier', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.Text(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=True),
    sa.Column('job_type', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('competition_index', sa.Float(), nullable=True),
    sa.Column('language_support', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_listings_id'), 'job_listings', ['id'], unique=False)
    op.create_table('market_intelligence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_category', sa.String(length=100), nullable=False),
    sa.Column('week_start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('trending_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('declining_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('saturation_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('salary_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('jd_count_analyzed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_category', 'week_start_date', name='uq_market_role_week')
    )
    op.create_index(op.f('ix_market_intelligence_role_category'), 'market_intelligence', ['role_category'], unique=False)
    op.create_index(op.f('ix_market_intelligence_week_start_date'), 'market_intelligence', ['week_start_date'], unique=False)
    op.create_table('market_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('skill_name', sa.String(length=150), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('demand_level', sa.String(), nullable=True),
    sa.Column('demand_velocity', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('avg_salary', sa.Float(), nullable=True),
    sa.Column('trending_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_signals_role_name'), 'market_signals', ['role_name'], unique=False)
    op.create_index(op.f('ix_market_signals_skill_name'), 'market_signals', ['skill_name'], unique=True)
    op.create_table('recruiter_personas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('company_context', sa.String(length=50), nullable=True),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('focus_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('communication_style', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('target_roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=150), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('min_projects', sa.Integer(), nullable=True),
    sa.Column('min_experience_years', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('salary_band_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('waitlist',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('referred_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('hiring_rubrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('role_category', sa.String(length=100), nullable=False),
    sa.Column('evaluation_criteria', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('passing_threshold', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('peer_benchmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=False),
    sa.Column('institution_tier', sa.String(length=20), nullable=False),
    sa.Column('ats_percentiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_percentiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('technical_percentiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('communication_percentiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_gap_percentiles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['target_roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'company_type', 'institution_tier', name='uq_benchmark_role_company_tier')
    )
    op.create_index(op.f('ix_peer_benchmarks_role_id'), 'peer_benchmarks', ['role_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('is_referral', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('career_paths',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_role_goal', sa.String(length=100), nullable=True),
    sa.Column('suggested_pivot', sa.String(length=100), nullable=True),
    sa.Column('reroute_reason', sa.Text(), nullable=True),
    sa.Column('milestones', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('market_synchronicity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cognitive_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('debugging_ability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('architecture_thinking', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ownership_mindset', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_under_pressure', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('dna_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dominant_archetype', sa.String(length=100), nullable=True),
    sa.Column('history_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('college_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('college_name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=True),
    sa.Column('naac_grade', sa.String(length=5), nullable=True),
    sa.Column('total_students', sa.Integer(), nullable=True),
    sa.Column('placement_officer_name', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('subscription_plan', sa.String(length=50), nullable=True),
    sa.Column('subscription_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_profiles_user_id'), 'college_profiles', ['user_id'], unique=True)
    op.create_table('external_calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('gamification_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('weekly_xp', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('current_streak_days', sa.Integer(), nullable=True),
    sa.Column('longest_streak_days', sa.Integer(), nullable=True),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('streak_freeze_count', sa.Integer(), nullable=True),
    sa.Column('earned_badges', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rank_global', sa.Integer(), nullable=True),
    sa.Column('rank_role', sa.Integer(), nullable=True),
    sa.Column('rank_institution', sa.Integer(), nullable=True),
    sa.Column('rank_weekly', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gamification_profiles_user_id'), 'gamification_profiles', ['user_id'], unique=True)
    op.create_table('gap_analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role_id', sa.UUID(), nullable=True),
    sa.Column('target_role_name', sa.String(length=100), nullable=False),
    sa.Column('company_type', sa.String(length=50), nullable=True),
    sa.Column('technical_gap_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_gap_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('project_gap_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_gap_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('consistency_gap_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('technical_gap_severity', sa.String(length=20), nullable=True),
    sa.Column('communication_gap_severity', sa.String(length=20), nullable=True),
    sa.Column('project_gap_severity', sa.String(length=20), nullable=True),
    sa.Column('confidence_gap_severity', sa.String(length=20), nullable=True),
    sa.Column('consistency_gap_severity', sa.String(length=20), nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('placement_probability', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expected_salary_band', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['target_role_id'], ['target_roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_mode', sa.String(length=50), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('difficulty_level', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_sessions_status'), 'interview_sessions', ['status'], unique=False)
    op.create_table('job_matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('skill_fit_score', sa.Float(), nullable=True),
    sa.Column('offer_probability_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(), nullable=True),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_id'), 'job_matches', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('action_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_letters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('letter_type', sa.String(length=20), nullable=False),
    sa.Column('readiness_score_at_generation', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('simulated_company', sa.String(length=150), nullable=True),
    sa.Column('simulated_role', sa.String(length=150), nullable=True),
    sa.Column('ctc_offered_thousands', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('letter_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offer_letters_user_id'), 'offer_letters', ['user_id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parent_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('student_user_id', sa.UUID(), nullable=False),
    sa.Column('relation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['student_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parent_profiles_student_user_id'), 'parent_profiles', ['student_user_id'], unique=False)
    op.create_index(op.f('ix_parent_profiles_user_id'), 'parent_profiles', ['user_id'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('target_company_type', sa.String(length=50), nullable=True),
    sa.Column('education_tier', sa.String(length=20), nullable=True),
    sa.Column('placement_readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_profiles_target_role'), 'profiles', ['target_role'], unique=False)
    op.create_table('psychometric_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('response_latency_by_topic', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avoidance_counts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_collapse_triggers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recovery_rate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('risk_appetite_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('persistence_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('dna_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dna_version', sa.Integer(), nullable=True),
    sa.Column('dna_computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hire_prob_service', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hire_prob_product', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hire_prob_startup', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hire_prob_faang', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sessions_required', sa.Integer(), nullable=True),
    sa.Column('sessions_completed', sa.Integer(), nullable=True),
    sa.Column('profile_type_label', sa.String(length=100), nullable=True),
    sa.Column('placement_probability_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_psychometric_profiles_user_id'), 'psychometric_profiles', ['user_id'], unique=True)
    op.create_table('recommendation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('interaction_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_listings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recruiters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('parsed_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_decay_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic_name', sa.String(length=150), nullable=False),
    sa.Column('mastery_level', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('stability_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('predicted_retention', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('alert_threshold', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('last_alert_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'topic_name', name='uq_skill_decay_user_topic')
    )
    op.create_index(op.f('ix_skill_decay_models_topic_name'), 'skill_decay_models', ['topic_name'], unique=False)
    op.create_index(op.f('ix_skill_decay_models_user_id'), 'skill_decay_models', ['user_id'], unique=False)
    op.create_table('student_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('college_name', sa.String(length=255), nullable=True),
    sa.Column('graduation_year', sa.SmallInteger(), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('github_url', sa.String(length=512), nullable=True),
    sa.Column('portfolio_url', sa.String(length=512), nullable=True),
    sa.Column('onboarding_step', sa.SmallInteger(), nullable=True),
    sa.Column('placement_readiness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_profiles_user_id'), 'student_profiles', ['user_id'], unique=True)
    op.create_table('subscriptions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('razorpay_subscription_id', sa.String(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revocation_reason', sa.String(length=255), nullable=True),
    sa.Column('last_active_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_auth_sessions_user_id'), 'user_auth_sessions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_roles', sa.Text(), nullable=True),
    sa.Column('preferred_locations', sa.Text(), nullable=True),
    sa.Column('min_salary_target', sa.Float(), nullable=True),
    sa.Column('remote_only', sa.Boolean(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('agent_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reasoning_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cognitive_load_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=False),
    sa.Column('load_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('contributing_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_taken', sa.String(length=100), nullable=True),
    sa.Column('difficulty_before', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('difficulty_after', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cognitive_load_events_session_id'), 'cognitive_load_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_cognitive_load_events_user_id'), 'cognitive_load_events', ['user_id'], unique=False)
    op.create_table('gap_recommendations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gap_analysis_id', sa.UUID(), nullable=False),
    sa.Column('time_horizon_days', sa.Integer(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=True),
    sa.Column('task_description', sa.Text(), nullable=False),
    sa.Column('resources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gap_analysis_id'], ['gap_analysis.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_audio_url', sa.String(length=512), nullable=True),
    sa.Column('response_latency_ms', sa.Integer(), nullable=True),
    sa.Column('hedging_word_count', sa.Integer(), nullable=True),
    sa.Column('ai_evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reward_signal', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cognitive_load_score', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('technical_correctness', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_clarity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('confidence_tone', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('completeness', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feedback_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('base_salary', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('bonus', sa.Float(), nullable=True),
    sa.Column('equity_text', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_id')
    )
    op.create_table('preparation_calendars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('gap_analysis_id', sa.UUID(), nullable=True),
    sa.Column('plan_type', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('daily_tasks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completion_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ics_key', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['gap_analysis_id'], ['gap_analysis.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ics_key')
    )
    op.create_index(op.f('ix_preparation_calendars_user_id'), 'preparation_calendars', ['user_id'], unique=False)
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('application_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('remind_at', sa.DateTime(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_value', sa.String(length=255), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('keyword_match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('completeness_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('quantified_achievements_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('action_verb_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('formatting_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('role_relevance_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('improvement_notes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reverse_interview_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('questions_asked', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_reactions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strategic_thinking_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('role_understanding_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('culture_fit_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('business_acumen_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('text_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_session_id'], ['interview_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reverse_interview_sessions_parent_session_id'), 'reverse_interview_sessions', ['parent_session_id'], unique=False)
    op.create_index(op.f('ix_reverse_interview_sessions_user_id'), 'reverse_interview_sessions', ['user_id'], unique=False)
    op.create_table('rl_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('difficulty_level', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('topic_performance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topic_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('topic_coverage', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_topic_tested', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reward_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('avg_time_per_answer_s', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('confidence_estimate', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('avoided_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('strong_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('weak_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optimal_session_length', sa.Integer(), nullable=True),
    sa.Column('last_session_id', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['last_session_id'], ['interview_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rl_states_user_id'), 'rl_states', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_pkey'))
    )
    op.create_table('languages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('compile_cmd', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('run_cmd', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source_file', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('languages_pkey'))
    )
    op.create_table('ar_internal_metadata',
    sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('ar_internal_metadata_pkey'))
    )
    op.create_table('schema_migrations',
    sa.Column('version', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version', name=op.f('schema_migrations_pkey'))
    )
    op.create_table('submissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_code', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('language_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stdin', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('expected_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stdout', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('time', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('memory', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stderr', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('number_of_runs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cpu_time_limit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cpu_extra_time', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('wall_time_limit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('memory_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('stack_limit', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_processes_and_or_threads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('enable_per_process_and_thread_time_limit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('enable_per_process_and_thread_memory_limit', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('max_file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('compile_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('exit_code', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('exit_signal', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('wall_time', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('compiler_options', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('command_line_arguments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('redirect_stderr_to_stdout', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('callback_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('additional_files', postgresql.BYTEA(), autoincrement=False, nullable=True),
    sa.Column('enable_network', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('submissions_pkey'))
    )
    op.create_index(op.f('index_submissions_on_token'), 'submissions', ['token'], unique=False)
    op.drop_index(op.f('ix_rl_states_user_id'), table_name='rl_states')
    op.drop_table('rl_states')
    op.drop_index(op.f('ix_reverse_interview_sessions_user_id'), table_name='reverse_interview_sessions')
    op.drop_index(op.f('ix_reverse_interview_sessions_parent_session_id'), table_name='reverse_interview_sessions')
    op.drop_table('reverse_interview_sessions')
    op.drop_table('resume_scores')
    op.drop_table('resume_entities')
    op.drop_table('reminders')
    op.drop_index(op.f('ix_preparation_calendars_user_id'), table_name='preparation_calendars')
    op.drop_table('preparation_calendars')
    op.drop_table('offers')
    op.drop_table('interview_scores')
    op.drop_table('interview_answers')
    op.drop_table('gap_recommendations')
    op.drop_index(op.f('ix_cognitive_load_events_user_id'), table_name='cognitive_load_events')
    op.drop_index(op.f('ix_cognitive_load_events_session_id'), table_name='cognitive_load_events')
    op.drop_table('cognitive_load_events')
    op.drop_table('application_events')
    op.drop_table('agent_evaluations')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_user_auth_sessions_user_id'), table_name='user_auth_sessions')
    op.drop_table('user_auth_sessions')
    op.drop_table('user_activities')
    op.drop_table('transactions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_student_profiles_user_id'), table_name='student_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_skill_decay_models_user_id'), table_name='skill_decay_models')
    op.drop_index(op.f('ix_skill_decay_models_topic_name'), table_name='skill_decay_models')
    op.drop_table('skill_decay_models')
    op.drop_table('sessions')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('recruiters')
    op.drop_table('recommendation_logs')
    op.drop_index(op.f('ix_psychometric_profiles_user_id'), table_name='psychometric_profiles')
    op.drop_table('psychometric_profiles')
    op.drop_index(op.f('ix_profiles_target_role'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_parent_profiles_user_id'), table_name='parent_profiles')
    op.drop_index(op.f('ix_parent_profiles_student_user_id'), table_name='parent_profiles')
    op.drop_table('parent_profiles')
    op.drop_table('otp_codes')
    op.drop_index(op.f('ix_offer_letters_user_id'), table_name='offer_letters')
    op.drop_table('offer_letters')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_job_matches_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_interview_sessions_status'), table_name='interview_sessions')
    op.drop_table('interview_sessions')
    op.drop_table('gap_analysis')
    op.drop_index(op.f('ix_gamification_profiles_user_id'), table_name='gamification_profiles')
    op.drop_table('gamification_profiles')
    op.drop_table('external_calendars')
    op.drop_index(op.f('ix_college_profiles_user_id'), table_name='college_profiles')
    op.drop_table('college_profiles')
    op.drop_table('cognitive_profiles')
    op.drop_table('career_paths')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_peer_benchmarks_role_id'), table_name='peer_benchmarks')
    op.drop_table('peer_benchmarks')
    op.drop_table('hiring_rubrics')
    op.drop_table('waitlist')
    op.drop_table('target_roles')
    op.drop_table('skills')
    op.drop_table('roles')
    op.drop_table('recruiter_personas')
    op.drop_index(op.f('ix_market_signals_skill_name'), table_name='market_signals')
    op.drop_index(op.f('ix_market_signals_role_name'), table_name='market_signals')
    op.drop_table('market_signals')
    op.drop_index(op.f('ix_market_intelligence_week_start_date'), table_name='market_intelligence')
    op.drop_index(op.f('ix_market_intelligence_role_category'), table_name='market_intelligence')
    op.drop_table('market_intelligence')
    op.drop_index(op.f('ix_job_listings_id'), table_name='job_listings')
    op.drop_table('job_listings')
    op.drop_index(op.f('ix_company_interview_profiles_profile_key'), table_name='company_interview_profiles')
    op.drop_table('company_interview_profiles')
    op.drop_table('companies')
    op.drop_table('badge_references')
    # ### end Alembic commands ###
