"""global_visions

Revision ID: cbd88559742b
Revises: c28b02963aa7
Create Date: 2026-06-21 23:59:25.111113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbd88559742b'
down_revision: Union[str, None] = 'c28b02963aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_truth_aggregates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('role_category', sa.String(length=100), nullable=False),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('quality_verified_count', sa.Integer(), nullable=False),
    sa.Column('stage_map', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_rounds', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('surprise_stages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('top_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline_reality', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ghost_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('offer_intelligence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('equity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_aggregated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name', 'role_category', name='uq_truth_company_role')
    )
    op.create_index(op.f('ix_company_truth_aggregates_company_name'), 'company_truth_aggregates', ['company_name'], unique=False)
    op.create_index(op.f('ix_company_truth_aggregates_role_category'), 'company_truth_aggregates', ['role_category'], unique=False)
    op.create_table('employer_truth_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('transparency_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('timeline_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ghost_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feedback_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('equity_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('submission_count', sa.Integer(), nullable=False),
    sa.Column('prev_month_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('last_computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_truth_scores_company_name'), 'employer_truth_scores', ['company_name'], unique=True)
    op.create_table('career_rebirth_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_domain', sa.String(length=100), nullable=True),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('career_break_reason', sa.String(length=100), nullable=True),
    sa.Column('break_duration_months', sa.Integer(), nullable=True),
    sa.Column('available_hours_per_week', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('weeks_to_completion', sa.Integer(), nullable=True),
    sa.Column('completion_target_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transferable_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('break_nullifier_strategy', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_rebirth_plans_user_id'), 'career_rebirth_plans', ['user_id'], unique=False)
    op.create_table('day_of_interview_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_company', sa.String(length=200), nullable=False),
    sa.Column('target_role', sa.String(length=200), nullable=False),
    sa.Column('interview_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('plan_generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('phase_1_warmup', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('phase_2_transition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('phase_3_launch', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_day_of_interview_plans_user_id'), 'day_of_interview_plans', ['user_id'], unique=False)
    op.create_table('employer_flags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('reported_by_user_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['reported_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employer_flags_company_name'), 'employer_flags', ['company_name'], unique=False)
    op.create_table('highschool_trajectories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('current_class', sa.Integer(), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=True),
    sa.Column('interest_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hours_per_week', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('years_to_placement', sa.Integer(), nullable=True),
    sa.Column('year_plans', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('milestones_completed', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_market_refresh_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_highschool_trajectories_user_id'), 'highschool_trajectories', ['user_id'], unique=True)
    op.create_table('language_progressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('primary_language', sa.String(length=10), nullable=False),
    sa.Column('current_bridge_phase', sa.Integer(), nullable=False),
    sa.Column('sessions_in_native', sa.Integer(), nullable=False),
    sa.Column('sessions_in_english', sa.Integer(), nullable=False),
    sa.Column('avg_technical_score_native', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_technical_score_english', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vocabulary_mastered', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('bridge_started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('phase_upgrade_dates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_language_progressions_user_id'), 'language_progressions', ['user_id'], unique=True)
    op.create_table('mentor_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('placement_company', sa.String(length=200), nullable=True),
    sa.Column('placement_role', sa.String(length=200), nullable=True),
    sa.Column('placement_ctc', sa.Integer(), nullable=True),
    sa.Column('college_name', sa.String(length=300), nullable=True),
    sa.Column('company_type', sa.String(length=30), nullable=True),
    sa.Column('commitment_start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('commitment_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sessions_committed', sa.Integer(), nullable=False),
    sa.Column('sessions_completed', sa.Integer(), nullable=False),
    sa.Column('mentees_active', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avg_mentee_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_profiles_user_id'), 'mentor_profiles', ['user_id'], unique=True)
    op.create_table('network_connections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_company', sa.String(length=200), nullable=False),
    sa.Column('target_role', sa.String(length=200), nullable=True),
    sa.Column('path_type', sa.String(length=30), nullable=False),
    sa.Column('connection_name', sa.String(length=300), nullable=False),
    sa.Column('connection_linkedin_url', sa.String(length=512), nullable=True),
    sa.Column('connection_company', sa.String(length=200), nullable=False),
    sa.Column('connection_role', sa.String(length=200), nullable=False),
    sa.Column('connection_college', sa.String(length=200), nullable=True),
    sa.Column('warmth_score', sa.Integer(), nullable=False),
    sa.Column('reachability_score', sa.Integer(), nullable=False),
    sa.Column('recommended_approach', sa.Text(), nullable=False),
    sa.Column('generated_outreach_message', sa.Text(), nullable=True),
    sa.Column('outreach_message_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_opted_in_consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_network_connections_target_company'), 'network_connections', ['target_company'], unique=False)
    op.create_index(op.f('ix_network_connections_user_id'), 'network_connections', ['user_id'], unique=False)
    op.create_table('real_interview_debriefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('interview_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=False),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=False),
    sa.Column('topics_tested', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('specific_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('what_worked', sa.Text(), nullable=True),
    sa.Column('what_did_not_work', sa.Text(), nullable=True),
    sa.Column('would_change', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('xp_reward_given', sa.Boolean(), nullable=False),
    sa.Column('is_quality_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_real_interview_debriefs_company_name'), 'real_interview_debriefs', ['company_name'], unique=False)
    op.create_index(op.f('ix_real_interview_debriefs_role'), 'real_interview_debriefs', ['role'], unique=False)
    op.create_index(op.f('ix_real_interview_debriefs_user_id'), 'real_interview_debriefs', ['user_id'], unique=False)
    op.create_table('referral_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('referrer_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('role_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('quarter', sa.String(length=10), nullable=False),
    sa.Column('referrer_note', sa.Text(), nullable=True),
    sa.Column('matched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=30), nullable=True),
    sa.Column('outcome_logged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referrer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referral_slots_candidate_id'), 'referral_slots', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_referral_slots_company_name'), 'referral_slots', ['company_name'], unique=False)
    op.create_index(op.f('ix_referral_slots_referrer_id'), 'referral_slots', ['referrer_id'], unique=False)
    op.create_table('skill_credentials',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('overall_prs', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sessions_completed', sa.Integer(), nullable=False),
    sa.Column('technical_depth', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('communication_clarity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('problem_solving', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('consistency_under_pressure', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('learning_velocity', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('code_quality', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('system_thinking', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('domain_expertise', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recruiter_summary', sa.Text(), nullable=True),
    sa.Column('credential_hash', sa.String(length=64), nullable=False),
    sa.Column('public_url', sa.String(length=300), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_credentials_credential_hash'), 'skill_credentials', ['credential_hash'], unique=True)
    op.create_index(op.f('ix_skill_credentials_user_id'), 'skill_credentials', ['user_id'], unique=True)
    op.create_table('talent_passports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('passport_id', sa.String(length=30), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('verified_role', sa.String(length=100), nullable=True),
    sa.Column('skill_tier', sa.String(length=20), nullable=True),
    sa.Column('prs_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('english_proficiency_tier', sa.String(length=100), nullable=True),
    sa.Column('eligible_company_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visa_pathways', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contractor_rate_min', sa.Integer(), nullable=True),
    sa.Column('contractor_rate_max', sa.Integer(), nullable=True),
    sa.Column('public_passport_url', sa.String(length=300), nullable=True),
    sa.Column('last_updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_passports_passport_id'), 'talent_passports', ['passport_id'], unique=True)
    op.create_index(op.f('ix_talent_passports_user_id'), 'talent_passports', ['user_id'], unique=True)
    op.create_table('mentor_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mentor_id', sa.UUID(), nullable=False),
    sa.Column('mentee_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('meeting_link', sa.String(length=300), nullable=True),
    sa.Column('agenda', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('mentor_rating', sa.Integer(), nullable=True),
    sa.Column('mentee_rating', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['mentee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mentor_id'], ['mentor_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_sessions_mentee_id'), 'mentor_sessions', ['mentee_id'], unique=False)
    op.create_index(op.f('ix_mentor_sessions_mentor_id'), 'mentor_sessions', ['mentor_id'], unique=False)
    op.create_table('outreach_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('connection_id', sa.UUID(), nullable=True),
    sa.Column('message_type', sa.String(length=30), nullable=False),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('specificity_score', sa.Integer(), nullable=True),
    sa.Column('reciprocity_score', sa.Integer(), nullable=True),
    sa.Column('action_clarity_score', sa.Integer(), nullable=True),
    sa.Column('length_score', sa.Integer(), nullable=True),
    sa.Column('response_ease_score', sa.Integer(), nullable=True),
    sa.Column('response_probability_estimate', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('issues_detected', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('improved_version', sa.Text(), nullable=True),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('was_sent', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_received', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['network_connections.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_messages_user_id'), 'outreach_messages', ['user_id'], unique=False)
    op.create_table('resume_ab_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_role', sa.String(length=200), nullable=False),
    sa.Column('target_company', sa.String(length=200), nullable=True),
    sa.Column('resume_a_id', sa.UUID(), nullable=False),
    sa.Column('resume_b_id', sa.UUID(), nullable=True),
    sa.Column('ats_score_a', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ats_score_b', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('signal_score_a', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('signal_score_b', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('winner', sa.String(length=1), nullable=True),
    sa.Column('difference_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['resume_a_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_b_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_ab_tests_user_id'), 'resume_ab_tests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resume_ab_tests_user_id'), table_name='resume_ab_tests')
    op.drop_table('resume_ab_tests')
    op.drop_index(op.f('ix_outreach_messages_user_id'), table_name='outreach_messages')
    op.drop_table('outreach_messages')
    op.drop_index(op.f('ix_mentor_sessions_mentor_id'), table_name='mentor_sessions')
    op.drop_index(op.f('ix_mentor_sessions_mentee_id'), table_name='mentor_sessions')
    op.drop_table('mentor_sessions')
    op.drop_index(op.f('ix_talent_passports_user_id'), table_name='talent_passports')
    op.drop_index(op.f('ix_talent_passports_passport_id'), table_name='talent_passports')
    op.drop_table('talent_passports')
    op.drop_index(op.f('ix_skill_credentials_user_id'), table_name='skill_credentials')
    op.drop_index(op.f('ix_skill_credentials_credential_hash'), table_name='skill_credentials')
    op.drop_table('skill_credentials')
    op.drop_index(op.f('ix_referral_slots_referrer_id'), table_name='referral_slots')
    op.drop_index(op.f('ix_referral_slots_company_name'), table_name='referral_slots')
    op.drop_index(op.f('ix_referral_slots_candidate_id'), table_name='referral_slots')
    op.drop_table('referral_slots')
    op.drop_index(op.f('ix_real_interview_debriefs_user_id'), table_name='real_interview_debriefs')
    op.drop_index(op.f('ix_real_interview_debriefs_role'), table_name='real_interview_debriefs')
    op.drop_index(op.f('ix_real_interview_debriefs_company_name'), table_name='real_interview_debriefs')
    op.drop_table('real_interview_debriefs')
    op.drop_index(op.f('ix_network_connections_user_id'), table_name='network_connections')
    op.drop_index(op.f('ix_network_connections_target_company'), table_name='network_connections')
    op.drop_table('network_connections')
    op.drop_index(op.f('ix_mentor_profiles_user_id'), table_name='mentor_profiles')
    op.drop_table('mentor_profiles')
    op.drop_index(op.f('ix_language_progressions_user_id'), table_name='language_progressions')
    op.drop_table('language_progressions')
    op.drop_index(op.f('ix_highschool_trajectories_user_id'), table_name='highschool_trajectories')
    op.drop_table('highschool_trajectories')
    op.drop_index(op.f('ix_employer_flags_company_name'), table_name='employer_flags')
    op.drop_table('employer_flags')
    op.drop_index(op.f('ix_day_of_interview_plans_user_id'), table_name='day_of_interview_plans')
    op.drop_table('day_of_interview_plans')
    op.drop_index(op.f('ix_career_rebirth_plans_user_id'), table_name='career_rebirth_plans')
    op.drop_table('career_rebirth_plans')
    op.drop_index(op.f('ix_employer_truth_scores_company_name'), table_name='employer_truth_scores')
    op.drop_table('employer_truth_scores')
    op.drop_index(op.f('ix_company_truth_aggregates_role_category'), table_name='company_truth_aggregates')
    op.drop_index(op.f('ix_company_truth_aggregates_company_name'), table_name='company_truth_aggregates')
    op.drop_table('company_truth_aggregates')
    # ### end Alembic commands ###
