from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from db.session import get_db
from schemas.interview import InterviewStartRequest, InterviewSessionResponse, AnswerSubmission, InterviewScorecard
from services.interview import engine
from api import deps
from db.models import User
from crud import crud_interview

router = APIRouter()

@router.post("/start", response_model=InterviewSessionResponse)
async def start_interview(
    request: InterviewStartRequest,
    current_user: User = Depends(deps.get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Start a new AI-driven interview session.
    Returns the first question generated by Claude.
    """
    session, first_question = await engine.start_interview(
        db, current_user, request.target_role, request.difficulty_level, request.session_mode
    )
    
    # Map to response model
    resp = InterviewSessionResponse.from_orm(session)
    resp.current_question = first_question
    return resp

@router.post("/{session_id}/answer")
async def submit_answer(
    session_id: str,
    submission: AnswerSubmission,
    current_user: User = Depends(deps.get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Submit an answer to the current question.
    Returns the next question or the final evaluation if the interview ends.
    """
    try:
        result = await engine.submit_answer(db, session_id, submission.answer_text, current_user)
        return result
    except ValueError as e:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="LLM processing failed")

@router.get("/history")
async def get_interview_history(
    current_user: User = Depends(deps.get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Returns candidate's past interview sessions.
    """
    from db.models import InterviewSession
    from sqlalchemy import select, desc
    stmt = select(InterviewSession).where(InterviewSession.user_id == current_user.id).order_by(desc(InterviewSession.started_at)).limit(20)
    sessions = (await db.execute(stmt)).scalars().all()
    return [
        {
            "id": str(s.id),
            "target_role": s.target_role,
            "status": s.status,
            "overall_score": s.overall_score,
            "created_at": s.started_at.isoformat() if s.started_at else None
        }
        for s in sessions
    ]

@router.get("/{session_id}/scorecard", response_model=InterviewScorecard)
async def get_scorecard(
    session_id: str,
    current_user: User = Depends(deps.get_current_active_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Retrieve the final scorecard and all turn data for a completed interview.
    """
    session = await crud_interview.get_session(db, session_id)
    if not session or session.user_id != current_user.id:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Session not found")
    return session


from pydantic import BaseModel
import uuid
from services import cognitive_load

class CognitiveLoadSubmit(BaseModel):
    session_id: uuid.UUID
    question_number: int
    backspace_rate: float
    average_delay_ms: float
    long_pauses_count: int
    word_count: int

@router.post("/cognitive-load")
async def submit_cognitive_load_batch(
    payload: CognitiveLoadSubmit,
    current_user: User = Depends(deps.get_current_active_user),
    db: AsyncSession = Depends(get_db)
) -> dict:
    """
    Submit real-time typing telemetry to compute and adapt to the student's cognitive load.
    """
    return await cognitive_load.record_cognitive_load_event(
        db=db,
        user_id=current_user.id,
        session_id=payload.session_id,
        question_number=payload.question_number,
        backspace_rate=payload.backspace_rate,
        average_delay_ms=payload.average_delay_ms,
        long_pauses_count=payload.long_pauses_count,
        word_count=payload.word_count
    )

